name: Send voting intentions by email

on:
  schedule:
    - cron: '0 0 * * *' # run every day at midnight

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests bs4 pandas

      - name: Scrape data and save to CSV
        run: python scraping.py

      - name: Send email
        uses: dawidd6/action-send-mail@v3.3.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Voting Intentions"
          body: "Please find attached the latest voting intentions."
          to: your_email@example.com
          attachments: |
            ./voting_intentions.csv